### PR TITLE
chore: update `node-pre-gyp` to secure version

### PR DESCRIPTION
**Pull request by nhodges**
`0.6.40` of `node-pre-gyp` includes the below commit, which updates dependencies upon `hoek` to a secure version. Making a PR to this because `firebase` has an upstream dependency on this package.

https://github.com/mapbox/node-pre-gyp/commit/eda90e0a27e585c7b4df37a81d45feaca0e443ee

```
$ nsp check
(+) 1 vulnerabilities found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Prototype pollution attack                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ hoek                                                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 4 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.16.3                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ firebase@4.10.0 > @firebase/firestore@0.3.3 >           │
│            │ grpc@1.9.1 > node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/566                             │
└────────────┴────────────────────────────────────────────────────────────────────┘

error Command failed with exit code 1.
```

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @nhodges isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by nhodges** [comment]
CLA signed.

**Comment by murgatroid99** [comment]
This isn't really going to accomplish much. node-pre-gyp is a bundled dependency of grpc, and it is a caret dependency, so the next build will pick up the new version anyway.

**Comment by murgatroid99** [comment]
Even more to the point, that version doesn't exist on npm. I think the better solution is to just upgrade to the newest version, which I am doing in #217.

**Pull request closed without merging**
