### PR TITLE
Add support for arm64 linux.

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
Closes issue #1405 

Info:
- Merges toolchain files into `linux.toolchain.cmake`
- Updates build image to use ubuntu and fixes issues with x86-only packages
- Updates build script
- Adds general linux/arm64 support to `grpc-node`

### CODE REVIEW

**Comment by murgatroid99** [comment]
I'm concerned about updating the base image to `ubuntu:22.04`. Historically, we have purposely run builds in an older environment to get compatibility with a wider range of glibc versions.

**Comment by murgatroid99** [comment]
OK, here are the options as I see them:

 - You get this to work with Debian Stretch
 - We use this change as is, and if there are issues with glibc compatibility I will revert this change.

**Comment by RedstoneWizard08** [comment]
I'll work on using debian stretch, or some other distro with the equivalent glibc version.

**Comment by RedstoneWizard08** [comment]
The main problem is finding the gcc binaries for debian stretch. I might end up pulling from the ubuntu repo and manually installing them.

**Comment by RedstoneWizard08** [comment]
@murgatroid99 I have chosen a better third option - using static linking. This allows it to run on hopefully any glibc version (as my research says) and it compiles well with cross. The cross-compilers are unavailable for debian stretch, and they work really well on Ubuntu Jammy. Older Ubuntu versions with older or the same glibc versions (I.E. Artful) don't have cross compilers.

**Comment by RedstoneWizard08** [comment]
@murgatroid99 I just fixed that, hopefully.

**Review by murgatroid99 — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
