### PR TITLE
Clean up linting

### PR DESCRIPTION
**Pull request by cjihrig**
This PR gets linting passing for the `@grpc/grpc-js` module. The third commit also removes unused variables (not including function parameters).

### CODE REVIEW

**Comment by cjihrig** [comment]
> I think if we actually want to do this, the linter needs to be part of the test suite.

Do you mean have it run as part of the `js.core.test` Gulp task?

**Comment by nicolasnoble** [comment]
Yes.

**Comment by cjihrig** [comment]
Added in https://github.com/grpc/grpc-node/pull/524/commits/985052c9ff8e9e53ba99f5bbc09718f91d610781.

**Comment by murgatroid99** [comment]
Can you resolve the merge conflicts? I'd do it myself on the web interface, but that doesn't give me access to the linter.

**Comment by cjihrig** [comment]
Done!

**Pull request merged**
