### PR TITLE
Add absl support

### PR DESCRIPTION
**Pull request by veblush**
Updated `grpc-native-core` project templates to add abseil targets properly.

Related to https://github.com/grpc/grpc/pull/20184.

### CODE REVIEW

**Comment by murgatroid99** [comment]
I have a similar change in #1232. Unfortunately there are other problems I have to fix before it will actually work.

**Comment by murgatroid99** [comment]
In the PR you linked to, the Node test and build jobs display a passing result. So, what prompted you to make those changes in the `binding.gyp.template` file?

**Comment by veblush** [comment]
It seems that we have a test with a head of grpc-node and changes from gRPC's PR. As you saw, I didn't have any failure with the PR but I thought that I needed some change on node.js like I did for other wrapped languages.

**Comment by veblush** [comment]
When I tried to build grpc-node, however, it didn't work well so I ended up with this PR. I think there must be a subtle difference, then?

**Pull request merged**
