### PR TITLE
Resolve new Buffer deprecation

### LINKED ISSUE #670: Buffer() Deprecation in Node 10+
### Problem description
I am using the static_gen of grpc_pb_js files with protoc cli tool

apparently, Buffer() is now Deprecated and has alternative methods:

    `DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

### Reproduction steps
1. generate pb.js & grpc_pb.js files using the following command:

    `protoc  --js_out=import_style=commonjs,binary:.  --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` *.proto`

2. use the generated files in your code
3. buffer error appears on request / response calls (couldn't find which of them triggers this specifically

### Environment
 - OS X 10.14.1
 - alpine latest (11.x), but this will happen on any node version from 10+
 - nvm
 - grpc-tools@1.6.6

### PR DESCRIPTION
**Pull request by shirbr510**
this PR comes to resolve #670 .

by doing so, I have done the following things:

- replaced all usages of `new Buffer` with `Buffer.from`
- changed default minimum node version to 6 to to EOL of older node versions

### CODE REVIEW

**Comment by shirbr510** [comment]
I Signed It

**Comment by shirbr510** [comment]
@thelinuxfoundation I Signed It

**Comment by murgatroid99** [comment]
Thank you for making this change. The script you used to do this modified a few comments that didn't need to change, so I would prefer that you change those back.

**Comment by murgatroid99** [comment]
Also, the tests are failing because some of the replacements are invalid. There are at least a few instances of `new Buffer(size)`, which should be replaced with `Buffer.alloc(size)`, not `Buffer.from(size)`.

**Comment by shirbr510** [comment]
Hi @murgatroid99 and thank you for the quick response!

I modified everything that you requested 👍 

let me know if I need to do any additional changes

**Comment by murgatroid99** [comment]
Thank you for your contribution

**Pull request merged**
