### PR TITLE
Make Windows build use OpenSSL built in to Node

### PR DESCRIPTION
**Pull request by murgatroid99**
Maybe this will just work.

EDIT: No such luck

### CODE REVIEW

**Comment by murgatroid99** [comment]
I don't think this is going to work, because I don't think nodejs/node#4932 was ever actually fixed.

**Comment by nicolasnoble** [comment]
It might be worth re-opening it somehow.

**Comment by nicolasnoble** [comment]
By the way, I meant re-opening the nodejs bug :-)

**Comment by murgatroid99** [comment]
See the latest update on that bug for why I'm trying this.

**Comment by murgatroid99** [comment]
OK, based on further updates to that issue it looks like this will not be a viable option in the near future.

**Pull request closed without merging**
