### PR TITLE
Wait for pending messages to be read before handling trailers

### PR DESCRIPTION
**Pull request by MiLk**
There are cases where trailers will be received before received message
could be processed by the filter stack.
This will wait for any message being processed by the filter stack to be
processed before handling the trailers.

This is a different attempt to resolve the issue already reported in #942

I'm using node v12.16.1.

### CODE REVIEW

**Comment by murgatroid99** [comment]
I believe this should be addressed in #1184. The new `maybeOutputStatus` method there explicitly checks for pending messages before propagating a status.

**Comment by MiLk** [comment]
#1184 seems to handle it differently, but doesn't solve the issue.

Here are traces of a simple call first with #1277, then with #1184.
```
2020-02-27T01:10:14.832Z | call_stream | [0] sending data chunk of length 29 (deferred)
2020-02-27T01:10:14.833Z | call_stream | [0] end() called
2020-02-27T01:10:14.833Z | call_stream | [0] calling end() on HTTP/2 stream
2020-02-27T01:10:14.854Z | call_stream | [0] received HTTP/2 headers frame
2020-02-27T01:10:14.855Z | call_stream | [0] receive HTTP/2 data frame of length 120
2020-02-27T01:10:14.856Z | call_stream | [0] parsed message of length 120
2020-02-27T01:10:14.857Z | call_stream | [0] filterReceivedMessage of length 120
2020-02-27T01:10:14.858Z | call_stream | [0] received HTTP/2 trailing headers frame
2020-02-27T01:10:14.858Z | call_stream | [0] received HTTP/2 end of data flag
2020-02-27T01:10:14.859Z | call_stream | [0] HTTP/2 stream closed with code 0
2020-02-27T01:10:14.859Z | call_stream | [0] unfilteredReadMessages.push message of length null
2020-02-27T01:10:14.860Z | call_stream | [0] pushing to reader message of length 198
2020-02-27T01:10:14.860Z | call_stream | [0] pushing to reader message of length null
2020-02-27T01:10:14.861Z | call_stream | [0] ended with status: code=0 details=""
2020-02-27T01:10:14.861Z | subchannel | 127.0.0.1:8443 callRefcount 1 -> 0
...
EXPECTED RESPONSE OUTPUT
...
2020-02-27T01:10:14.866Z | subchannel | 127.0.0.1:8443 refcount 2 -> 1
2020-02-27T01:10:14.866Z | resolving_load_balancer | 127.0.0.1:8443 READY -> SHUTDOWN
2020-02-27T01:10:14.866Z | connectivity_state | 127.0.0.1:8443 READY -> SHUTDOWN
2020-02-27T01:10:14.866Z | connectivity_state | 127.0.0.1:8443 SHUTDOWN -> SHUTDOWN
2020-02-27T01:10:14.866Z | subchannel | 127.0.0.1:8443 refcount 1 -> 0
2020-02-27T01:10:14.866Z | subchannel | 127.0.0.1:8443 READY -> TRANSIENT_FAILURE
```

```
2020-02-27T01:11:13.705Z | call_stream | [0] sending data chunk of length 29 (deferred)
2020-02-27T01:11:13.705Z | call_stream | [0] calling end() on HTTP/2 stream
2020-02-27T01:11:13.735Z | call_stream | [0] received HTTP/2 headers frame
2020-02-27T01:11:13.737Z | call_stream | [0] receive HTTP/2 data frame of length 120
2020-02-27T01:11:13.737Z | call_stream | [0] parsed message of length 120
2020-02-27T01:11:13.738Z | call_stream | [0] filterReceivedMessage of length 120
2020-02-27T01:11:13.740Z | call_stream | [0] received HTTP/2 trailing headers frame
2020-02-27T01:11:13.741Z | call_stream | [0] ended with status: code=0 details=""
2020-02-27T01:11:13.742Z | call_stream | [0] HTTP/2 stream closed with code 8
2020-02-27T01:11:13.742Z | call_stream | [0] ended with status: code=1 details="Call cancelled"
2020-02-27T01:11:13.742Z | subchannel | 127.0.0.1:8443 callRefcount 1 -> 0
Error: 1 CANCELLED: Call cancelled
    at Object.callErrorFromStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/client.js:149:37)
    at Object.onReceiveStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:113:27)
    at Http2CallStream.maybeOutputStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:152:22)
    at Http2CallStream.endCall (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:139:18)
    at ClientHttp2Stream.<anonymous> (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:360:22)
    at ClientHttp2Stream.emit (events.js:311:20)
    at emitCloseNT (internal/streams/destroy.js:69:8) {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
2020-02-27T01:11:13.745Z | subchannel | 127.0.0.1:8443 refcount 2 -> 1
2020-02-27T01:11:13.745Z | resolving_load_balancer | 127.0.0.1:8443 READY -> SHUTDOWN
2020-02-27T01:11:13.745Z | connectivity_state | 127.0.0.1:8443 READY -> SHUTDOWN
2020-02-27T01:11:13.745Z | connectivity_state | 127.0.0.1:8443 SHUTDOWN -> SHUTDOWN
2020-02-27T01:11:13.745Z | subchannel | 127.0.0.1:8443 refcount 1 -> 0
2020-02-27T01:11:13.745Z | subchannel | 127.0.0.1:8443 READY -> TRANSIENT_FAILURE
```

After adding some more traces, I get the following:
```
2020-02-27T01:56:11.268Z | call_stream | [0] received HTTP/2 headers frame
2020-02-27T01:56:11.269Z | call_stream | [0] receive HTTP/2 data frame of length 120
2020-02-27T01:56:11.269Z | call_stream | [0] parsed message of length 120
Trace: filterReceivedMessage
    at Http2CallStream.filterReceivedMessage (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:195:17)
    at Http2CallStream.tryPush (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:215:18)
    at ClientHttp2Stream.<anonymous> (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:318:26)
    at ClientHttp2Stream.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at ClientHttp2Stream.Readable.push (_stream_readable.js:209:10)
    at Http2Stream.onStreamRead (internal/stream_base_commons.js:186:23)
2020-02-27T01:56:11.270Z | call_stream | [0] filterReceivedMessage of length 120
2020-02-27T01:56:11.271Z | call_stream | [0] received HTTP/2 trailing headers frame
Trace: endCall
    at Http2CallStream.endCall (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:129:15)
    at Http2CallStream.handleTrailers (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:245:14)
    at ClientHttp2Stream.emit (events.js:311:20)
    at emit (internal/http2/core.js:297:8)
    at processTicksAndRejections (internal/process/task_queues.js:87:22)
2020-02-27T01:56:11.272Z | call_stream | [0] ended with status: code=0 details=""
2020-02-27T01:56:11.273Z | call_stream | [0] HTTP/2 stream closed with code 8
Trace: endCall
    at Http2CallStream.endCall (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:129:15)
    at ClientHttp2Stream.<anonymous> (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:364:22)
    at ClientHttp2Stream.emit (events.js:311:20)
    at emitCloseNT (internal/streams/destroy.js:69:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2020-02-27T01:56:11.274Z | call_stream | [0] ended with status: code=1 details="Call cancelled"
2020-02-27T01:56:11.274Z | subchannel | 127.0.0.1:8443 callRefcount 1 -> 0
Error: 1 CANCELLED: Call cancelled
    at Object.callErrorFromStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/client.js:149:37)
    at Object.onReceiveStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:113:27)
    at Http2CallStream.maybeOutputStatus (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:140:18)
    at ClientHttp2Stream.<anonymous> (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:364:22)
    at ClientHttp2Stream.emit (events.js:311:20)
    at emitCloseNT (internal/streams/destroy.js:69:8) {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
2020-02-27T01:56:11.276Z | resolving_load_balancer | 127.0.0.1:8443 IDLE -> SHUTDOWN
2020-02-27T01:56:11.276Z | connectivity_state | 127.0.0.1:8443 IDLE -> SHUTDOWN
2020-02-27T01:56:11.276Z | connectivity_state | 127.0.0.1:8443 SHUTDOWN -> SHUTDOWN
2020-02-27T01:56:11.276Z | subchannel | 127.0.0.1:8443 refcount 1 -> 0
2020-02-27T01:56:11.277Z | subchannel | 127.0.0.1:8443 IDLE -> TRANSIENT_FAILURE
Trace: handleFilteredRead
    at Http2CallStream.handleFilteredRead (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:171:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by murgatroid99** [comment]
OK, I want to clarify, we do not intend to have a guarantee that all messages are processed before a non-OK status is propagated up.

**Comment by MiLk** [comment]
The status code is supposed to be 0, so I don't know why the new implementation gives a CANCELLED.

**Comment by MiLk** [comment]
It seems that while `outputStatus` is not called (as expected), `endCall` is called, destroying the stream, triggering `maybeOutputStatus` with a non-OK status, which causes the issue.

**Comment by murgatroid99** [comment]
That's a good point. I think the solution there is to not process http2 stream errors after the trailers have been processed. Alternatively, `destroyHttp2Stream` should send different `RST_STREAM` codes based on the status.

I've added both of those changes to #1184. I think that should resolve the issues you're seeing.

**Comment by MiLk** [comment]
I gave a quick run at your latest code, it seems the message is still dropped and the call stays stuck.
```
2020-02-28T02:04:14.017Z | call_stream | [0] attachHttp2Stream from subchannel 127.0.0.1:8443
2020-02-28T02:04:14.017Z | call_stream | [0] sending data chunk of length 5 (deferred)
2020-02-28T02:04:14.017Z | call_stream | [0] calling end() on HTTP/2 stream
2020-02-28T02:04:14.040Z | call_stream | [0] received HTTP/2 headers frame
2020-02-28T02:04:14.041Z | call_stream | [0] receive HTTP/2 data frame of length 1659
2020-02-28T02:04:14.042Z | call_stream | [0] parsed message of length 1659
2020-02-28T02:04:14.042Z | call_stream | [0] filterReceivedMessage of length 1659
2020-02-28T02:04:14.043Z | call_stream | [0] received HTTP/2 trailing headers frame
2020-02-28T02:04:14.044Z | call_stream | [0] ended with status: code=0 details=""
2020-02-28T02:04:14.045Z | call_stream | [0] HTTP/2 stream closed with code 8
Trace: handleFilteredRead with final status: {
  code: 0,
  details: '',
  metadata: Metadata { internalRepr: Map { 'date' => [Array] }, options: {} }
}
    at Http2CallStream.handleFilteredRead (/Users/emilien/Dev/grpc-node/packages/grpc-js/build/src/call-stream.js:169:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


2020-02-28T02:04:43.983Z | call_stream | [0] ended with status: code=4 details="Deadline exceeded"
```

**Comment by murgatroid99** [comment]
Oh, I see what the problem is: `handleFilteredRead` drops messages if the call has ended. You're running into this more with compression because that adds an extra asynchronous delay to handling incoming messages.

**Comment by murgatroid99** [comment]
I've made another change that should actually fix it. The overall issue was that reads weren't getting processed if there was a status, and an OK status wouldn't get emitted if there were still reads to be processed.

**Comment by MiLk** [comment]
It seems to be working now.
Thanks 🎉

**Comment by murgatroid99** [comment]
That PR has now been published in version 0.7.0

**Pull request closed without merging**
