### PR TITLE
Build Electron 4.2 artifacts

### PR DESCRIPTION
**Pull request by CapOM**
4.0 and 4.1 were there but not 4.2

https://github.com/grpc/grpc-node/issues/937

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @CapOM isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by CapOM** [comment]
Hi @nicolasnoble , please take a look, thx!

**Comment by murgatroid99** [comment]
Thank you for helping with this. It would be even more helpful to have a PR with this change against the `grpc@1.22.x` branch so that we can publish the new binaries for that version.

**Comment by CapOM** [comment]
@murgatroid99 backport submitted https://github.com/grpc/grpc-node/pull/944 .
Can I send PR for 1.20.x and 1.21.x ?

**Pull request merged**
