### PR TITLE
Updated doc in readme.md

### PR DESCRIPTION
**Pull request by tomasAlabes**
Explaining the option to change the location of the precompiled-binaries. Related to #441 and #117.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @tomasAlabes isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by tomasAlabes** [comment]
CLA signed

**Comment by tomasAlabes** [comment]
@thelinuxfoundation CLA signed

**Comment by tomasAlabes** [comment]
@murgatroid99 I already signed it. Now I can only view the CLA in the foundation's site, but not sign it again. If this comment doesn't work maybe closing and reopening the PR could work?

**Comment by nicolasnoble** [comment]
Nope, everything is good now.

**Pull request merged**
