### PR TITLE
proto-loader: include Google well known protos

### PR DESCRIPTION
**Pull request by cjihrig**
This is a draft PR. It is not complete yet because there was some push back in #771 about implementing this in protobufjs, and I'd like feedback on the general approach taken. Since almost 3 weeks have passed with no response from protobufjs, I decided to open a WIP PR.

This commit ensures that the Google well known protos are available because protobufjs only exposes a subset of them.

Fixes: https://github.com/grpc/grpc-node/issues/771

### CODE REVIEW

**Comment by murgatroid99** [comment]
Most of the well-known protos are already loadable with Protobuf.js, and the ones that aren't are located in `protobufjs/google/protobuf`, so we should just be able to use those instead of getting them from another library like `grpc-tools`. If something is missing from both of those sets, it's probably worth just leaving out until someone needs it. The `compiler/plugin.proto` file, for example, is only useful for writing a plugin for `protoc`.

We probably want to use something like [get-installed-path](https://www.npmjs.com/package/get-installed-path) to consistently access that directory.

**Comment by cjihrig** [comment]
> Most of the well-known protos are already loadable with Protobuf.js, and the ones that aren't are located in protobufjs/google/protobuf, so we should just be able to use those instead of getting them from another library like grpc-tools.

Right. I wasn't sure if there was any chance of the ones bundled with protobufjs being out of date. Using their copy simplifies things, and if I've checked properly, only `compiler/plugin.proto` is missing, which should be fine.

Do you want the well known protos available all of the time, or behind an option?

**Comment by murgatroid99** [comment]
It should just load them all the time. I don't think optimizing for load time is worthwhile because it's something you should be doing infrequently, and the alternative of a load failure when you don't pass the option is not valuable.

**Comment by cjihrig** [comment]
OK, I've made them load unconditionally. I also added a second commit to fix the lint. If you're OK with this, I can remove the draft status.

**Comment by murgatroid99** [comment]
Instead of having the extra build step, I would prefer to just load the 3 or 4 extra files that we need directly from the protobuf.js directory at runtime either when the package is loaded or the first time a user tries to load a proto file.

**Comment by xblv** [comment]
Hi @murgatroid99 @cjihrig could we publish a new version of proto-loader npm package? on npm this still of version 0.4.0.
Or since I am quite new with npm with git, Is there a way to directly use up-to-date code of proto-loader package? thanks.

**Comment by nicolasnoble** [comment]
@xblv check https://docs.npmjs.com/cli/install, there are several parts talking about how to install from something local, from git, github, or other means.

**Comment by murgatroid99** [comment]
This has now been published in version 0.5.0 of the library.

**Pull request merged**
