### PR TITLE
Remove broken build badge from README

### PR DESCRIPTION
**Pull request by MasterOdin**
PR replaces the build badge in the README from one used from Travis (which the repo doesn't use) with one provided by GH actions.

### CODE REVIEW

**Comment by murgatroid99** [comment]
I think that badge would also be potentially misleading. It only describes the grpc-tools package build, and doesn't represent anything about the primary library in this repository (grpc-js).

**Comment by MasterOdin** [comment]
It doesn't look like there is a GH action for `grpc-js`, only for `grpc-tools`? Should there be a workflow that runs the tests for `grpc-js` or something?

**Comment by murgatroid99** [comment]
The grpc-js tests are run elsewhere, and there isn't a badge for it. I think removing the badge entirely is the best option.

**Comment by MasterOdin** [comment]
Done

**Review by murgatroid99 — APPROVED** [review]

**Comment by murgatroid99** [comment]
Thank you for taking the time to improve this.

**Pull request merged**
