### PR TITLE
grpc-js: fix unit test and add semver  types

### PR DESCRIPTION
**Pull request by RenShine**
I want to patch some function,But the unit test is bad, So first mention a pr to fix with the problem of unit testing

The content of this PR is the result of running `npm run fix` and `npm i @types/semver`

### CODE REVIEW

**Comment by RenShine** [comment]
> What problem is this solving?

Unit tests will report many errors, because unit tests include eslint, you can run npm run test if this pr is not included, many errors will be reported

**Comment by murgatroid99** [comment]
OK, I understand fixing the formatting, but why install `@types/semver`? The package doesn't even have a dependency on `semver` anymore.

**Comment by RenShine** [comment]
> OK, I understand fixing the formatting, but why install `@types/semver`? The package doesn't even have a dependency on `semver` anymore.

Used in gulpfile.ts, I moved it to devDependencies

**Comment by murgatroid99** [comment]
OK, I can accept that. Please update from master and sign the CLA, then I can merge this.

**Comment by murgatroid99** [comment]
Thank you for your contribution, but this change has been superseded by #1837.

The issue with the `@types/semver` dependency can be addressed by running `npm install` in the root of the repository.

**Pull request closed without merging**
