### PR TITLE
Bump to v1.20.0

### PR DESCRIPTION
**Pull request by murgatroid99**
I need to write something here.

### CODE REVIEW

**Comment by brandonros** [comment]
What else needs to be done to get 1.20.0 to npm?

**Comment by nicolasnoble** [comment]
Building packages, and publishing. Pressing buttons, that is.

**Comment by brandonros** [comment]
@nicolasnoble Thanks for the swift response. Am I able to push those buttons? If not, are those buttons are expected to be pushed by the end of day today?

**Comment by murgatroid99** [comment]
Currently this is something only we can do, and I have done it. v1.20.0 is now out.

**Comment by brandonros** [comment]
Thank you so much!

**Pull request merged**
