### PR TITLE
Add missing license files to package directories

### PR DESCRIPTION
**Pull request by murgatroid99**
Also fill in the copyright holder and year, and make sure all instances of the file are identical.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Some are a bit weird. We'll chat :-)

**Comment by johnjbarton** [comment]
? The Copyrights are all nonsense in the final commit?

**Comment by murgatroid99** [comment]
@johnjbarton If you are referring to the `Copyright {yyyy} {name of copyright owner}` line in each file, that is part of the LICENSE file's appendix that describes text to include in code files. As far as I can tell, it is not meant to be filled in in the LICENSE file itself.

**Comment by johnjbarton** [comment]
Just above the line in question we read:
```
      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "{}"
      replaced with your own identifying information.
```
I assume that the LICENSE appears here "to apply the Apache License to your work".  

To be sure, the thing that makes sense to me is for every user of Apache 2.0 to publish a LICENSE file consisting of the  filled-in copyright line and the remaining 20 odd lines in the file, roughly looking like BSD or MIT license. The entire content before LICENSE can be "look it up and enjoy".  But somehow we are in a world where the LICENSE contains instructions to apply the LICENSE which cannot be followed without ruining the LICENSE.

**Comment by nicolasnoble** [comment]
You've left out the important part right after your quote:

```
The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.
```

Aka, one needs to attach this and replace the appropriate template phrases _in the source code_. For instance, like this: https://raw.githubusercontent.com/grpc/grpc-node/master/packages/grpc-native-core/ext/byte_buffer.cc

**Comment by johnjbarton** [comment]
Hey, I prefer you interpretation.  

So then what do we make of 
https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/channel-credentials.ts ?

Note that you publish grpc-js with just the LICENSE AFAICT.

**Comment by nicolasnoble** [comment]
That's indeed a mistake, thanks for pointing it out.

**Comment by nicolasnoble** [comment]
See #793.

**Pull request merged**
