### PR TITLE
Build arm64 binaries for mac

### PR DESCRIPTION
**Pull request by hayashikun**
For now, pre-compiled binary of `grpc-tools` is missing for M1 mac (arm64).
 
https://github.com/grpc/grpc-node/issues/1405

It is possible to run M1 mac by setting `npm_config_target_arch=x64`, but it is a little bit messy.

It must be straightforward to wait for M1 build machines in GitHub action, 
https://github.com/grpc/grpc-node/issues/1405#issuecomment-1195903603

but we can build universal binaries by setting `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"` to `cmake`, and can extract binaries for x86_64/arm64 using `lipo`.
Or, it would be good to provide universal binaries without separating binaries.

In my Macbook (intel), I can successfully build both x86_64 and arm64 binaries.

```
$ uname -v
Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
$ cd grpc-node
$ ./packages/grpc-tools/build_binaries.sh
$ cd ./artifacts/grpc-tools/v1.11.2
$ tar -xvf darwin-arm64.tar.gz && tar -xvf darwin-x86_64.tar.gz

$ file x86_64/*
x86_64/grpc_node_plugin: Mach-O universal binary with 1 architecture: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64]
x86_64/grpc_node_plugin (for architecture x86_64):      Mach-O 64-bit executable x86_64
x86_64/protoc:           Mach-O universal binary with 1 architecture: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64]
x86_64/protoc (for architecture x86_64):        Mach-O 64-bit executable x86_64

$ file arm64/*
arm64/grpc_node_plugin: Mach-O universal binary with 1 architecture: [arm64:Mach-O 64-bit executable arm64Mach-O 64-bit executable arm64]
arm64/grpc_node_plugin (for architecture arm64):        Mach-O 64-bit executable arm64
arm64/protoc:           Mach-O universal binary with 1 architecture: [arm64:Mach-O 64-bit executable arm64Mach-O 64-bit executable arm64]
arm64/protoc (for architecture arm64):  Mach-O 64-bit executable arm64
```

### CODE REVIEW

**Comment by murgatroid99** [comment]
I ran the build job with this PR, and you can see the result in the PR status checks. Can you manually verify that the artifact produced by the Mac build job works on M1?

**Comment by hayashikun** [comment]
Thanks for running CI.
The artifact built by CI works well in my M1 mac (Macbook Pro).

I uploaded produced artifacts by CI to s3 buckets, and I installed `grpc-tools` in my M1 mac by the following procedure.
https://github.com/grpc/grpc-node/issues/1405#issuecomment-1213149448

I can successfully installed after setting `grpc_tools_binary_host_mirror` in `.npmrc`.
Then, I compiled [example.proto](https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto) using npm installed binaries (that is artifacts built by CI mac).

```
$ uname -m -s
Darwin arm64

$ npm install grpc-tools
added 57 packages, and audited 58 packages in 2s

4 packages are looking for funding
  run `npm fund` for details

$ ./node_modules/grpc-tools/bin/protoc example.proto --plugin=protoc-gen-grpc=./node_modules/grpc-tools/bin/grpc_node_plugin --grpc_out=. 
$ ls
example.proto  example_grpc_pb.js  node_modules  package-lock.json  package.json
```

As long as I confirmed, they work well.

**Review by murgatroid99 — COMMENTED** [review]
That's good enough for me. Thank you for your contribution.

**Comment by murgatroid99** [comment]
This has been published in grpc-tools version 1.11.3.

**Comment by yurks** [comment]
something weird with that "new" arm64 binaries:

https://github.com/grpc/grpc-node/issues/2378

**Pull request merged**
