### PR TITLE
Fix development vulnerabilities

### PR DESCRIPTION
**Pull request by bjornstar**
## What I am Addressing

Currently on master when I do an `npm install` I get a deprecation warning and an audit with 56 vulnerabilities.

### Before
```
$ > npm i
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> fsevents@1.2.9 install /Users/bjornstar/grpc-node/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/bjornstar/grpc-node/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
added 1082 packages from 874 contributors and audited 12211 packages in 16.106s
found 56 vulnerabilities (4 low, 48 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
$ >
```

### After
```
$ > npm i

> fsevents@1.2.9 install /Users/bjornstar/grpc-node/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/bjornstar/grpc-node/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
added 823 packages from 1050 contributors and audited 10263 packages in 13.204s
found 0 vulnerabilities

$ >
```

### A summary of my changes
The majority of the vulnerabilities relate to the old version of `nyc` in this package. Upgrading `nyc` to the latest version fixes all but 6 vulnerabilities. Updating `mocha` and related packages resolves the rest.

#### Why change the gulpfiles from .ts to .js?
The most recent version of `nyc` has a number of changes that affect how files are included. Combining `gulp`, `nyc`, and `ts-node` ended up causing `ts-node` to be registered twice. Considering these files did not make much use out of typescript, the easiest solution to get coverage with the latest version was to convert them back to javascript.

#### What dev-dependencies have changed?
Upgraded
- `gulp-jsdoc3` from `v1.0.1` to `v2.0.0`
- `gulp-mocha` from `v4.3.1` to `v7.0.1`
- `mocha` from `v3.5.3` to `v6.2.0`
- `mocha-jenkins-reporter` from `v0.3.9` to `v0.4.2`

Removed
- `gulp-tslint` was `v8.1.1`
- `gulp-typescript` was `v3.2.2`
- `gulp-util` was `v3.0.8`

### CODE REVIEW

**Comment by murgatroid99** [comment]
Unfortunately it looks like it's not quite that simple. The tests are failing with errors running the gulp scripts. It looks like gulp-mocha is the first culprit.

**Comment by murgatroid99** [comment]
For some reason all of the test jobs are taking a lot longer even though we are testing on fewer versions. I'll rerun the tests again to verify.

**Comment by bjornstar** [comment]
> For some reason all of the test jobs are taking a lot longer even though we are testing on fewer versions. I'll rerun the tests again to verify.

It looks like the tests in `grpc-native-core` weren't fully cleaning up.

**Comment by murgatroid99** [comment]
This change updates multiple libraries by multiple major versions. Each of those changes could have significant impact on how this plays out.

**Comment by bjornstar** [comment]
I'm no longer working on this.

**Pull request closed without merging**
