### PR TITLE
Delete grpc-native-core from master, along with all references

### PR DESCRIPTION
**Pull request by murgatroid99**
I also copied some `.proto` files that were being referenced from the submodule into `test/proto`.

Output of `git grep -- -core`:

```
README.md:Directory: [`packages/grpc-native-core`](https://github.com/grpc/grpc-node/tree/grpc@1.24.x/packages/grpc-native-core) (lives in the `grpc@1.24.x` branch) (see here for installation information)
packages/grpc-native-core/README.md:The `grpc` npm pacakge previously lived in this package. It has been removed. It now lives in the [`grpc@1.24.x` branch](https://github.com/grpc/grpc-node/tree/grpc%401.24.x/packages/grpc-native-core) where bugfixes are still being applied.
```

In the `test` directory tests that test all combinations of client and server from both libraries, I removed only the set that uses both the client and server from the native library, and I switched to installing the native library from `npm` instead of using the local copy. This way, we can still test that `grpc-js` matches the behavior of `grpc`, and I think the interop tests should still work.

After/in parallel to this, I think I can easily migrate the `grpc-tools` build to a GitHub Workflow and remove the Kokoro build tests entirely. I would also like to migrate the regular tests to a GitHub Workflow, but there doesn't seem to currently be a good way to get the per-test reports that we currently have.

### CODE REVIEW

**Comment by murgatroid99** [comment]
It is expected that the Electron build jobs fail, because I deleted those config files and build scripts.

**Comment by murgatroid99** [comment]
The Windows Build Job has been failing due to an issue that is fixed in #1422. That is probably the reason it is failing here.

The Mac build job config files were also deleted so I expect that to fail too.

**Comment by merlinnot** [comment]
My offer still stands 🙂 https://github.com/grpc/grpc-node/issues/1170

**Comment by murgatroid99** [comment]
@merlinnot Do you know how to get good per-test output comparable to [what we currently get from Kokoro](https://source.cloud.google.com/results/invocations/5b5a3b15-3d6e-4b1a-97fc-345c5f37a495/targets/github%2Fgrpc-node%2Freports%2Fnode12/tests) from GitHub Actions?

**Comment by merlinnot** [comment]
That looks similar to GitHub annotations. I personally only used that for ESLint before, to annotate errors and warnings, but it looks like people are also using it for failed tests:

fail

Did I understand your intention correctly, to have an output with failures only?

**Comment by murgatroid99** [comment]
Yes, that looks like what I'm looking for: separate reports for each test failure, along with specific output from each test. I found [mocha-github-actions-reporter](https://github.com/daniellockyer/mocha-github-actions-reporter) which probably does that, though I'm not entirely sure how it's used.

**Pull request merged**
