### PR TITLE
Execute tests on Node.js 11

### PR DESCRIPTION
**Pull request by kibertoad**
Add Node.js 11 to Travis configuration

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @kibertoad isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by kibertoad** [comment]
Not going to sign CLA just for this, but anyone with CLA signed is welcome to fork my branch and get this merged.

**Comment by kibertoad** [comment]
@nicolasnoble Why have travis.yaml then?..

**Comment by nicolasnoble** [comment]
Leftovers from another life. For the node11 support, you can follow along in #593.

**Pull request closed without merging**
