### PR TITLE
Stop using lodash's template generator.

### LINKED ISSUE #453: GRPC Prevents Content Security Policy from working without including 'unsafe-eval'
**In GRPC-node 1.11.3:**

```
var log_template = _.template(
    '{severity} {timestamp}\t{file}:{line}]\t{message}',
    {interpolate: /{([\s\S]+?)}/g});
```

The use of `lodash`'s `_.template` function requires `eval` in a production environment. It seems kind of needless that this function is used here for something as mundane as logging, given the security implications. Is it avoidable?

### PR DESCRIPTION
**Pull request by nicolasnoble**
Fixes #453.

### CODE REVIEW

**Comment by murgatroid99** [comment]
Add semicolons please, including after the `}`

**Comment by nicolasnoble** [comment]
Ah, right.

**Comment by Slapbox** [comment]
@nicolasnoble that was quick!

**Comment by nicolasnoble** [comment]
Thanks :-) Granted, this was a really easy fix.

Also, for the follow up: we're backporting this fix to our 1.13 branch, and
we are getting firebase to update their grpc dependency.

**Pull request merged**
