### PR TITLE
Adding fix to ignore self-signed certificates verification

### PR DESCRIPTION
**Pull request by vinothsa4891**
Adding fix to ignore self-signed certificates verification

### CODE REVIEW

**Comment by vinothsa4891** [comment]
https://github.com/grpc/grpc-node/issues/2811

**Comment by murgatroid99** [comment]
In the referenced issue, you mention that the Go implementation accomplishes this with a TLS credentials option. I think we should take the same approach in Node, rather than introducing a new channel option. Both `credentials.createSsl` and `credetials.createFromSecureContext` have a `verifyOptions` argument that this option would fit in.

**Comment by vinothsa4891** [comment]
I tried with verifyOptions checkServerIdentity: () => null, but with this, I was able to disable only the hostname/CN name verification. I'm still getting error for self signed certificate. I see only rejectUnauthorized: false to bypass the verification of self-signed certificates and allows the client to make SSL requests without validating the server’s SSL certificate @murgatroid99

**Comment by murgatroid99** [comment]
I am suggesting that instead of adding a channel option, we add a field to `verifyOptions` called `rejectUnauthorized` that gets passed along to the connection options.

**Comment by vinothsa4891** [comment]
@murgatroid99  - I tried that even before , But its not working. Getting "err Error: 14 UNAVAILABLE: No connection established. Last error: self-signed certificate in certificate chain"

const verifyOptions = {
      // Define checkServerIdentity function
      checkServerIdentity: (host, cert) => {
        // Here you can add custom certificate validation logic if needed
    
        // Returning undefined means accepting the certificate
        // Throwing an error will reject the connection
        return undefined; // Accept the certificate
      },
      rejectUnauthorized: false,
  };
  
  const sslCreds = grpc.credentials.createSsl(
      null,
      null,
      null,
      verifyOptions
    );

    return new this._grpcObj.RegistryApi(
      "<< url >>:443",
      sslCreds,
    );

**Review by murgatroid99 — APPROVED** [review]

**Pull request merged**
