### PR TITLE
Fix link comparison

### PR DESCRIPTION
**Pull request by yofriadi**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @yofriadi isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by murgatroid99** [comment]
Bypassing tests because this is purely a documentation change.

**Comment by murgatroid99** [comment]
@yofriadi Thank you for your contribution, but I can't merge it unless you sign our CLA.

**Comment by yofriadi** [comment]
@murgatroid99 could you please look for the CLA, I can't register on that, the verifying email operation never give me email confirmation.

**Comment by yofriadi** [comment]
@murgatroid good news, I already signed the CLA, you can merge now

**Comment by murgatroid99** [comment]
Thank you for bringing this to our attention. It has now been fixed as part of #510.

**Pull request closed without merging**
