### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by agmt5989**
Corrected a few typos and semantics in the readme file.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @agmt5989 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by agmt5989** [comment]
I have signed the CLA, not sure why it's still marked as an active requirement.

**Comment by murgatroid99** [comment]
@thelinuxfoundation

**Comment by murgatroid99** [comment]
Thank you for your contribution.

**Pull request merged**
