### PR TITLE
Add request/response type to method definition

### PR DESCRIPTION
**Pull request by kurayama**
Adds the resolved request/response type to `grpc-loader` method definition.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @kurayama isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by nicolasnoble** [comment]
@kurayama thank you for your contribution, but in order for us to accept it, we'd need you to follow the instructions provided by the CLA bot ☝️. Thanks!

**Comment by kurayama** [comment]
@nicolasnoble done

**Comment by murgatroid99** [comment]
Thank you for your contribution, but we cannot accept it. One of the design goals of this library was to avoid directly exposing the API of Protobuf.js, and this change would break that. I understand the value of exposing this information, and I would be open to suggestions about other ways to do it.

**Pull request closed without merging**
