### PR TITLE
Add LICENSE file from project root.

### PR DESCRIPTION
**Pull request by johnjbarton**
Lawyers want to see the LICENSE.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @johnjbarton isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by johnjbarton** [comment]
I'm just guessing because I don't know how you build for npm.

**Comment by murgatroid99** [comment]
The file paths in `package.json` are relative to the directory it's in, so you can't just include a file from the root directory. Doing this will require either adding a copy of the LICENSE to that directory or adding a `prepublishOnly` script to copy it into that directory.

**Comment by murgatroid99** [comment]
@thelinuxfoundation Hopefully a comment from anyone will get this to recheck the CLA.

**Pull request merged**
