### PR TITLE
Sticking on a more reproducible node version.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Tentatively fixes #355.

**Comment by jtattermusch** [comment]
I tried to test this PR locally and it seems that it's not helping with #355.  

The revert https://github.com/grpc/grpc/pull/15471 does seem to fix the problem though, so let's approve and merge it to get green tests and investigate then.

**Comment by nicolasnoble** [comment]
How are you reproducing locally exactly ?

**Comment by jtattermusch** [comment]
I added locally update `https://github.com/grpc/grpc/blob/master/tools/run_tests/helper_scripts/run_grpc-node.sh`

with 

```
git clone --recursive https://github.com/nicolasnoble/grpc-node ./../grpc-node
cd ./../grpc-node
git checkout node4
```

**Pull request closed without merging**
