### PR TITLE
adds sometimes required Host header to proxy connection

### PR DESCRIPTION
**Pull request by bbesset**
my corporate proxy requires the Host header to be defined to the target host, orelse it returns a 403 error

### CODE REVIEW

**Comment by murgatroid99** [comment]
For future reference for anyone else looking at this PR, the [HTTP CONNECT spec](https://httpwg.org/specs/rfc7231.html#CONNECT) says to include the Host header with this value.

**Comment by murgatroid99** [comment]
Thank you for the contribution. I can't merge it until you resolve the CLA issue.

**Comment by bbesset** [comment]
thank you

it took me a while, but the CLA issue is resolved now.

**Review by murgatroid99 — APPROVED** [review]

**Pull request merged**
