### PR TITLE
Script changes to allow testing from grpc/grpc

### PR DESCRIPTION
**Pull request by matt-kwong**

### CODE REVIEW

**Comment by murgatroid99** [comment]
You might also have to add "--unsafe-perm" to npm install calls in a couple of the gulpfiles

**Comment by matt-kwong** [comment]
@murgatroid99 With the changes from #33 , should I just remove `npm install --unsafe-perm` all together from `run-tests.sh`? The npm installs in the gulpfiles have been changed to add `--unsafe-perm`.

**Comment by murgatroid99** [comment]
The `npm install` in `run-tests.sh` was moved, but it's still there. You should still change it just to be safe.

**Comment by matt-kwong** [comment]
I was able to get testing from grpc/grpc to work locally with this branch, PTAL.

**Pull request merged**
