### PR TITLE
grpc-tools: Update protoc to v3.19.1

### PR DESCRIPTION
**Pull request by natiz**

### CODE REVIEW

**Comment by murgatroid99** [comment]
It's not that simple to make this upgrade. See my comment at https://github.com/grpc/grpc-node/pull/2155#issuecomment-1177903304

**Comment by natiz** [comment]
Thanks for pointing it out!

I've set it [v3.19.1](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.1) which seems to be the last release that includes javascript changes.
I am specifically interested in https://github.com/protocolbuffers/protobuf/pull/8864 which is included in [v3.19.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.0)

**Comment by murgatroid99** [comment]
That should be fine, but unfortunately I can't accept any change without the EasyCLA check. Please fix that.

**Comment by natiz** [comment]
I think its related to https://github.com/protocolbuffers/protobuf/commit/c47adad0c32e55b63f183c22af7a4d6bc09b3f1a (and [this](https://github.com/grpc/grpc-node/blob/master/packages/grpc-tools/CMakeLists.txt#L24-L26)), but fiddling in the dark here. I'll try to resolve it.

**Comment by natiz** [comment]
Fixed the windows build

**Comment by murgatroid99** [comment]
I had to push a fix for the Linux build. Can you merge from master to pick it up?

**Comment by murgatroid99** [comment]
That `cmake_minimum_required(VERSION 3.15)` line is going to be an issue. We want to run the build on the oldest possible Debian LTS release, for maximum compatibility, but the latest Debian LTS version is Buster, which only has cmake 3.13.4.

**Comment by natiz** [comment]
Updated to 3.7, since I got this for 3.13: `CMake 3.13 or higher is required.  You are running version 3.7.2`

**Comment by murgatroid99** [comment]
OK, it works. Can you also update the version in the package.json to 1.12.0 so that I can publish the change immediately?

**Comment by natiz** [comment]
Sure, bumped.

**Review by murgatroid99 — APPROVED** [review]
Thank you for your contribution.

**Comment by murgatroid99** [comment]
I have published this in version 1.12.0.

**Comment by natiz** [comment]
Looks like there is an issue with the binaries in 1.12.0, they are placed in a subfolder `GNUSparseFile.0`, which causes an `ENOENT` failure on `bin/protoc`.

1.12.0:
```
> find node_modules/grpc-tools/bin
node_modules/grpc-tools/bin
node_modules/grpc-tools/bin/protoc.js
node_modules/grpc-tools/bin/google
node_modules/grpc-tools/bin/google/protobuf
node_modules/grpc-tools/bin/google/protobuf/timestamp.proto
node_modules/grpc-tools/bin/google/protobuf/field_mask.proto
node_modules/grpc-tools/bin/google/protobuf/api.proto
node_modules/grpc-tools/bin/google/protobuf/duration.proto
node_modules/grpc-tools/bin/google/protobuf/struct.proto
node_modules/grpc-tools/bin/google/protobuf/wrappers.proto
node_modules/grpc-tools/bin/google/protobuf/source_context.proto
node_modules/grpc-tools/bin/google/protobuf/any.proto
node_modules/grpc-tools/bin/google/protobuf/type.proto
node_modules/grpc-tools/bin/google/protobuf/empty.proto
node_modules/grpc-tools/bin/google/protobuf/compiler
node_modules/grpc-tools/bin/google/protobuf/compiler/plugin.proto
node_modules/grpc-tools/bin/google/protobuf/descriptor.proto
node_modules/grpc-tools/bin/GNUSparseFile.0
node_modules/grpc-tools/bin/GNUSparseFile.0/grpc_node_plugin
node_modules/grpc-tools/bin/GNUSparseFile.0/protoc
node_modules/grpc-tools/bin/protoc_plugin.js
```

1.11.3:
```
> find node_modules/grpc-tools/bin
node_modules/grpc-tools/bin
node_modules/grpc-tools/bin/grpc_node_plugin
node_modules/grpc-tools/bin/protoc.js
node_modules/grpc-tools/bin/google
node_modules/grpc-tools/bin/google/protobuf
node_modules/grpc-tools/bin/google/protobuf/timestamp.proto
node_modules/grpc-tools/bin/google/protobuf/field_mask.proto
node_modules/grpc-tools/bin/google/protobuf/api.proto
node_modules/grpc-tools/bin/google/protobuf/duration.proto
node_modules/grpc-tools/bin/google/protobuf/struct.proto
node_modules/grpc-tools/bin/google/protobuf/wrappers.proto
node_modules/grpc-tools/bin/google/protobuf/source_context.proto
node_modules/grpc-tools/bin/google/protobuf/any.proto
node_modules/grpc-tools/bin/google/protobuf/type.proto
node_modules/grpc-tools/bin/google/protobuf/empty.proto
node_modules/grpc-tools/bin/google/protobuf/compiler
node_modules/grpc-tools/bin/google/protobuf/compiler/plugin.proto
node_modules/grpc-tools/bin/google/protobuf/descriptor.proto
node_modules/grpc-tools/bin/protoc
node_modules/grpc-tools/bin/protoc_plugin.js
```

**Pull request merged**
