### PR TITLE
Fixes #1804

### LINKED ISSUE #1804: Issue with typescript 4.1
### Problem description
Since typescript 4.1, the promise resolution typing has changed.
This change is documented [here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#resolves-parameters-are-no-longer-optional-in-promises) and well known.

### Reproduction steps
Opened the following branch to demonstrate the issue.

Running `npm install` or `npm run compile`

```
> @grpc/grpc-js@1.2.12 compile /Users/florentvilmart/src/grpc/grpc-node/packages/grpc-js
> tsc -p .

src/call-credentials.ts:118:23 - error TS2345: Argument of type '{ [index: string]: string; } | undefined' is not assignable to parameter of type '{ [index: string]: string; } | PromiseLike<{ [index: string]: string; }>'.
  Type 'undefined' is not assignable to type '{ [index: string]: string; } | PromiseLike<{ [index: string]: string; }>'.

118               resolve(headers);
                          ~~~~~~~

src/server-call.ts:511:13 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?

511             resolve();
                ~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.promise.d.ts:33:34
    33     new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'value' was not provided.

src/server-call.ts:518:11 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?

518           resolve();
              ~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.promise.d.ts:33:34
    33     new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'value' was not provided.
```

### Environment
 - Mac OS 11.2.3
 - Node version v14.15.0
 - Package name and version [@grpc/grpc-js@1.2.12]

### PR DESCRIPTION
**Pull request by flovilmart**
Updates call-credentials.ts and server-call.ts to properly match the type definitions

### CODE REVIEW

**Comment by murgatroid99** [comment]
It doesn't make sense to make changes for compatibility with a type checker that we're not going to use. If we're going to do this at all, leave the `typescript` version upgrade in place so that it will continue to verify the correctness of these types. Though, it would be best to switch to a `~` dependency because as mentioned, Microsoft makes breaking changes to `typescript` in minor version bumps.

**Comment by flovilmart** [comment]
@murgatroid99 the issue is present when consuming the this module from a project that uses typescript >= 4.1.
For some reason, the `.ts` files in the `src` folder of the distributed package get picked up when importing this module.

In the PR the bump of typescript is reverted; and thus the changes are valid in all versions of typescript.

**Comment by murgatroid99** [comment]
I am having trouble reproducing that error by importing `@grpc/grpc-js`. Can you share some code that results in that error?

**Comment by flovilmart** [comment]
So I triple checked with `tsc --traceResolution` and the error occurs because we have the following:

```
import { status } from '@grpc/grpc-js';
import { ServerErrorResponse } from '@grpc/grpc-js/src/server-call';


export class InvalidArgumentError implements ServerErrorResponse {

  readonly code = status.INVALID_ARGUMENT;
}
```

Switching to the following fixes the issue:

```
import { ServerErrorResponse } from '@grpc/grpc-js/build/src/server-call';
```

Feel free to close

**Comment by murgatroid99** [comment]
Right, I'm closing this. We'll make this change later as part of a general `typescript` version upgrade. #1807 should help.

**Comment by flovilmart** [comment]
Wonderful! Thanks!

**Pull request closed without merging**
