### PR TITLE
Update to v1.25.0

### PR DESCRIPTION
**Pull request by murgatroid99**
We're a bit late publishing this.

### CODE REVIEW

**Comment by Jakeeyturner** [comment]
Hey @murgatroid99,

Just wondering when you were hoping to have this PR merged by? (And presumably the 1.25.0 binaries published)

Thank you!
Jake

**Comment by murgatroid99** [comment]
Our build is broken because of problems separate from the changes in this PR, so we need to fix it first

**Comment by cazfletch** [comment]
Hi @murgatroid99 is there any update about when this pr will be merged?

**Comment by murgatroid99** [comment]
We are actively working on fixing our build. When it is fixed we will resume publishing the library.

**Comment by reversemerman** [comment]
@murgatroid99 : Any update on this one?

**Pull request closed without merging**
