### PR TITLE
Set the default port of 80 explicitly in http_proxy

### LINKED ISSUE #1608: Problem with http proxy at port 80
### Problem description
There is a wrong proxy port problem when using this library with a proxy server which has the same port as the scheme.

### Reproduction steps
If I have proxy set up at port 80 : `$http_proxy=www.myproxy.com:80` . The "80" will be stripped as a result of the URL library because the 80 is the default port of http scheme. As a result, in the later steps at the `resolver-dns.js`, a default port value "443" will be used (instead of using port 80 in my $http_proxy) which will caused the wrong port issue for further steps.
### Environment
 - OS name, version and architecture: [Fedora Release 31]
 - Node version [12.16.3]
 - Node installation method [nvm]
 - Package name and version [1.1.7]

### Additional context
I'm using the google dialogflow with the proxy setup
Here is my $http_proxy: http://myproxyserver.com:80
Here is my GRPC log:
2020-10-21T16:48:46.025Z | proxy | Proxy server myproxyserver.com set by environment variable grpc_proxy
2020-10-21T16:48:46.027Z | proxy | No proxy server list set by environment variable no_proxy
2020-10-21T16:48:46.029Z | resolving_load_balancer | dns:myproxyserver.com IDLE -> IDLE
2020-10-21T16:48:46.030Z | connectivity_state | dns:myproxyserver.com IDLE -> IDLE
2020-10-21T16:48:46.032Z | dns_resolver | Resolver constructed for target dns:myproxyserver.com
2020-10-21T16:48:46.045Z | channel | dns:myproxyserver.com createCall [0] method="/google.cloud.dialogflow.v2.Sessions/DetectIntent", deadline=Wed Oct 21 2020 11:49:46 GMT-0500 (Central Daylight Time)
2020-10-21T16:48:46.050Z | call_stream | [0] Sending metadata
2020-10-21T16:48:46.052Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-10-21T16:48:46.066Z | call_stream | [0] write() called with message of length 102
2020-10-21T16:48:46.067Z | call_stream | [0] end() called
2020-10-21T16:48:46.070Z | call_stream | [0] deferring writing data chunk of length 107
2020-10-21T16:48:46.071Z | dns_resolver | Resolution update requested for target dns:myproxyserver.com
2020-10-21T16:48:46.075Z | resolving_load_balancer | dns:myproxyserver.com IDLE -> CONNECTING
2020-10-21T16:48:46.078Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-10-21T16:48:46.078Z | connectivity_state | dns:myproxyserver.com IDLE -> CONNECTING
2020-10-21T16:48:46.078Z | resolving_load_balancer | dns:myproxyserver.com CONNECTING -> CONNECTING
2020-10-21T16:48:46.079Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-10-21T16:48:46.079Z | connectivity_state | dns:myproxyserver.com CONNECTING -> CONNECTING
2020-10-21T16:48:46.083Z | dns_resolver | Resolved addresses for target dns:myproxyserver.com: [xxx.xxx.xxx.xxx:443]
2020-10-21T16:48:46.094Z | pick_first | Connect to address list xxx.xxx.xxx.xxx:443
2020-10-21T16:48:46.097Z | subchannel | xxx.xxx.xxx.xxx:443 refcount 0 -> 1
2020-10-21T16:48:46.097Z | subchannel | xxx.xxx.xxx.xxx:443 refcount 1 -> 2
2020-10-21T16:48:46.098Z | pick_first | Start connecting to subchannel with address xxx.xxx.xxx.xxx:443
2020-10-21T16:48:46.099Z | pick_first | IDLE -> CONNECTING
2020-10-21T16:48:46.100Z | resolving_load_balancer | dns:myproxyserver.com CONNECTING -> CONNECTING
2020-10-21T16:48:46.101Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-10-21T16:48:46.101Z | connectivity_state | dns:myproxyserver.com CONNECTING -> CONNECTING
2020-10-21T16:48:46.102Z | subchannel | xxx.xxx.xxx.xxx:443 IDLE -> CONNECTING
2020-10-21T16:48:46.104Z | proxy | Using proxy xxx.xxx.xxx.xxx:443 to connect to dialogflow.googleapis.com:443
2020-10-21T16:48:46.114Z | pick_first | CONNECTING -> CONNECTING
2020-10-21T16:48:46.115Z | resolving_load_balancer | dns:myproxyserver.com CONNECTING -> CONNECTING
2020-10-21T16:48:46.115Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-10-21T16:48:46.115Z | connectivity_state | dns:myproxyserver.com CONNECTING -> CONNECTING
Failed to connect to proxy xxx.xxx.xxx.xxx:443 with error connect ECONNREFUSED xxx.xxx.xxx.xxx:443
2020-10-21T16:48:46.126Z | subchannel | xxx.xxx.xxx.xxx:443 CONNECTING -> TRANSIENT_FAILURE
2020-10-21T16:48:46.127Z | pick_first | CONNECTING -> TRANSIENT_FAILURE
2020-10-21T16:48:46.127Z | resolving_load_balancer | dns:myproxyserver.com CONNECTING -> TRANSIENT_FAILURE
2020-10-21T16:48:46.128Z | channel | Pick result: TRANSIENT_FAILURE subchannel: undefined status: 14 No connection established
2020-10-21T16:48:46.128Z | call_stream | [0] cancelWithStatus code: 14 details: "No connection established"
2020-10-21T16:48:46.129Z | call_stream | [0] ended with status: code=14 details="No connection established"
2020-10-21T16:48:46.130Z | connectivity_state | dns:myproxyserver.com CONNECTING -> TRANSIENT_FAILURE
2020-10-21T16:48:46.217Z | channel | dns:myproxyserver.com createCall [1] method="/google.cloud.dialogflow.v2.Sessions/DetectIntent", deadline=Wed Oct 21 2020 11:49:46 GMT-0500 (Central Daylight Time)

I think we need to change the way that where we used the Default port in resolver-dns.js if the behavior(omit the default port) of URL package is expected

### PR DESCRIPTION
**Pull request by murgatroid99**
This fixes #1608.

### CODE REVIEW

**Review by nicolasnoble — APPROVED** [review]

**Comment by anhem115** [comment]
Hi, thank for the fix, do you have an estimation for the released date?

**Comment by murgatroid99** [comment]
I think it should be soon. A few changes have piled up that need to be packaged into a minor release, and we're working on finalizing those.

**Comment by anhem115** [comment]
Thank you very much.

**Comment by murgatroid99** [comment]
I have published this patch in version 1.1.8

**Comment by mohan570** [comment]
Hi Murgatroid99,

Am having issue while using dialogflow node js client with grpc/grpc-js ,

find below the error 

ERROR: Error: Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443
 at Http2CallStream.<anonymous> (API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\client.js:102:45)
 at Http2CallStream.emit (events.js:322:22)
 at Http2CallStream.endCall (API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call-stream.js:74:18)
 at API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call-stream.js:355:18
 at runMicrotasks (<anonymous>)
 at processTicksAndRejections (internal/process/task_queues.js:97:5) {
 code: 'ECONNREFUSED',
 details: 'Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443',
 metadata: Metadata { internalRepr: Map {} }

**Comment by murgatroid99** [comment]
@mohan570 That error is not related to this PR. Please file a separate issue about it.

**Pull request merged**
