### PR TITLE
Added a 100MB maxBuffer since the default 200kb is too small

### PR DESCRIPTION
**Pull request by OlivierBoucher**
Hi guys,

I ran into this issue where stdout maxBuffer is too small on a large proto codebase. This fixes the issue, 1MB is fair but I can adjust it per your liking.

Also, was not sure if master is the good branch, let me know and I'll re-submit

### CODE REVIEW

**Comment by murgatroid99** [comment]
What is the impact of having a maxBuffer size that is too small?

**Comment by OlivierBoucher** [comment]
The process crashes

**Comment by murgatroid99** [comment]
I think that if the impact is that bad, we should probably have a wider safety margin. This script should only be run on development machines, and it only spawns one process, so I think 100MB or even 1GB would be reasonable.

**Comment by OlivierBoucher** [comment]
@murgatroid99 friendly ping -- submitted the proper changes

**Comment by olivierboucher** [comment]
@murgatroid99 friendly ping. This issue is still on going since grpc-tools has to be released

**Pull request merged**
