### PR TITLE
PSM Interop: simplify Kokoro buildscripts

### PR DESCRIPTION
**Pull request by sergiitk**
Integrates the new features of the the Kokoro PSM Interop install library introduced in grpc/psm-interop#73.

Nearly all common functionality was moved from per-language/per-branch PSM Interop build scripts to [psm_interop_kokoro_lib.sh](https://github.com/grpc/psm-interop/blob/main/.kokoro/psm_interop_kokoro_lib.sh):
1. The list of tests in the each test suite 
2. Per-test-suite flag customization
3. `run_test` methods
4. `build_docker_images_if_needed` methods
5. Generic `build_test_app_docker_images` methods (simple docker build + docker push + docker tag). grpc-java is one exception, as it doesn't run docker directly, but a cloudbuild flow.

Now all PSM Interop jobs share the same buildscripts by all test suites:
1.  buildscript that invokes the test: `psm-interop-test-{language}.sh` (configured as `build_file` in the build cfg)
2. buildscript that builds the xDS test client/server and publishes them as a Docker image: `psm-interop-build-{language}.sh` (conventional name called from `psm_interop_kokoro_lib.sh`)

`psm-interop-test-{language}.sh`:
1. Sets `GRPC_LANGUAGE`, `BUILD_SCRIPT_DIR` environment variables.
2. Downloads the shared `psm_interop_kokoro_lib.sh` from the main branch of the psm-interop repo.
3. Sources `psm-interop-build-{language}.sh`
4. Calls `psm::run "${PSM_TEST_SUITE}"` (`PSM_TEST_SUITE` configured in the cfg file).

`psm-interop-build-{language}.sh`:
1. Defines `psm::lang::build_docker_images` which is called from `psm_interop_kokoro_lib.sh`.
2. Invokes any repo-specific logic.
3. May use `psm::build::docker_images_generic` for generic Docker build, tag, push, or provide implement its own build/publish method.

References:
- b/288578634
- See the full list of the new features at grpc/psm-interop#73.
- Additional fixes to the shared lib: grpc/psm-interop#78, grpc/psm-interop#79

### CODE REVIEW

**Comment by sergiitk** [comment]
Using grpc/psm-interop#73 / grpc/psm-interop@1c0f169:

- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/2cd61b0b-c97b-4e00-9850-2ee38a4a8b94)

**Comment by sergiitk** [comment]
Using grpc/psm-interop#73 / grpc/psm-interop@1afd454:

- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/c822e492-4962-4cdd-871e-89cd16756862)

**Comment by sergiitk** [comment]
Using grpc/psm-interop#73 / grpc/psm-interop@8f28619:

- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/66c432fb-2e79-4bc5-adee-aa6a8d5ed922)

**Comment by sergiitk** [comment]
Using grpc/psm-interop#73 / grpc/psm-interop@5aeb13f:

Full LB test run.

- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/43dbaaaf-1741-4e9b-886e-2289c0c9b71c)

**Review by gnossen — APPROVED** [review]

**Comment by sergiitk** [comment]
The last check using the install script from `main`:
- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/4cd64922-56e7-4643-a136-995772eb1fea)
- [ ] [grpc/node/master/xds_k8s_url_map](https://source.cloud.google.com/results/invocations/08edab63-d557-4fcb-a6dd-3e3a713227ae)

**Comment by sergiitk** [comment]
Please merge it yet. I'd like to wait until I got approvals on the same change from the rest of the repos. So we don't have to do another set of backports if anything comes up.

**Comment by sergiitk** [comment]
Using grpc/psm-interop@2cbdfd:
- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/59f78821-adde-4484-8b03-f50e9ef2a43c)
- [ ] [grpc/node/master/xds_k8s_url_map](https://source.cloud.google.com/results/invocations/57e7be63-f091-47f3-ae9a-fee890da33c5)

**Comment by sergiitk** [comment]
- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/9677cfb3-17e4-41e1-bc76-efc8fb127c52)

**Comment by sergiitk** [comment]
Just to stay on the safe side, ad-hoc run after squashing all commits and rebasing against master:
- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/7e6bb33e-7d09-41bc-9846-525657825069)

**Pull request merged**
