### PR TITLE
Fix auto-generated service definition

### PR DESCRIPTION
**Pull request by EduardoLaranjo**
relate to issue #1766

### CODE REVIEW

**Comment by murgatroid99** [comment]
This looks like a good change, but I can't accept it until you sign the CLA. Also, please run `npm run compile` and `npm run generate-golden` to regenerate the golden test files, and add the results to this PR.

**Comment by EduardoLaranjo** [comment]
hi @murgatroid99 I will do that

**Comment by EduardoLaranjo** [comment]
hi @murgatroid99 where are the proto files located

**Comment by murgatroid99** [comment]
I think you have to update git submodules to get them (`git submodule update --init --recursive`).

**Comment by EduardoLaranjo** [comment]
Yup that worked, appreciated 👍.

**Review by murgatroid99 — APPROVED** [review]
Thank you for your contribution

**Pull request merged**
